backend:
  source_1:
    image_repo: mock-user/backend_api
    launch_template_id: lt-mock-backend-123
    asg_name: asg-backend-mock
    region: local-test-1
    port: 3001
    health_path: /health
    instance_warmup: 30
    min_healthy_percent: 90
    user_data_template: ssm
    ssm_param_name: ssm-backend-image